name: Enable GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Enable GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api --method PUT \
            -H "Accept: application/vnd.github.v3+json" \
            /repos/badrpk/rangoons/pages \
            -f source.branch='main' \
            -f source.path='/'
